# Generated by Django 3.2.13 on 2026-01-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0058_merge_0029_crop_name_spanish_0057_auto_20260122_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxpermissionpages',
            options={'ordering': ('name',)},
        ),
    ]
