# Generated by Django 3.2.13 on 2026-02-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0059_alter_wxpermissionpages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualstationdatafile',
            name='is_manually_validated',
            field=models.BooleanField(default=False),
        ),
    ]
