# Generated by Django 3.2.13 on 2026-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0060_manualstationdatafile_is_manually_validated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcpersistthreshold',
            options={'ordering': ('station', 'variable', 'window')},
        ),
        migrations.AlterModelOptions(
            name='qcrangethreshold',
            options={'ordering': ('station', 'variable', 'month')},
        ),
        migrations.AlterModelOptions(
            name='qcstepthreshold',
            options={'ordering': ('station', 'variable')},
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='persistence',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Manual) Persistence Variance'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='persistence_hourly',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Automatic) Persistence Variance'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='persistence_window',
            field=models.IntegerField(blank=True, null=True, verbose_name='Global threshold (Manual) Persistence Window (in hours)'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='persistence_window_hourly',
            field=models.IntegerField(blank=True, null=True, verbose_name='Global threshold (Automatic) Persistence Window (in hours)'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='range_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Manual) Range Max'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='range_max_hourly',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Automatic) Range Max'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='range_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Manual) Range Min'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='range_min_hourly',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Automatic) Range Min'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='step',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Manual) Step'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='step_hourly',
            field=models.FloatField(blank=True, null=True, verbose_name='Global threshold (Automatic) Step'),
        ),
        migrations.AlterUniqueTogether(
            name='qcpersistthreshold',
            unique_together={('station', 'variable')},
        ),
        migrations.AlterUniqueTogether(
            name='qcrangethreshold',
            unique_together={('station', 'variable', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='qcstepthreshold',
            unique_together={('station', 'variable')},
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='qcpersistthreshold',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='qcrangethreshold',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='qcstepthreshold',
            name='interval',
        ),
    ]
