# Generated by Django 3.2.13 on 2026-03-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0061_auto_20260222_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxPermissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='wxpermissionpages',
            options={'ordering': ('category__sort_order', 'category__name', 'name')},
        ),
        migrations.AddField(
            model_name='wxpermissionpages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='wx.wxpermissioncategory'),
        ),
    ]
