# Generated by Django 3.2.13 on 2026-03-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0062_auto_20260305_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxpermissionpages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='wx.wxpermissioncategory'),
        ),
    ]
