# Generated by Django 3.2.13 on 2026-03-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0063_alter_wxpermissionpages_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WxGroupPermission',
        ),
        migrations.DeleteModel(
            name='WxPermission',
        ),
    ]
