# Generated by Django 3.2.13 on 2026-04-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0065_alter_maintenancereportequipment_maintenance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereportequipment',
            name='maintenance_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.maintenancereport'),
        ),
    ]
