# Generated by Django 3.2.13 on 2026-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0066_alter_maintenancereportequipment_maintenance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereportequipment',
            name='equipment_order',
            field=models.CharField(choices=[('P', 'Primary Equipment'), ('S', 'Secondary Equipment')], default='P', max_length=1),
        ),
    ]
