# Generated by Django 3.2.13 on 2026-04-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0067_alter_maintenancereportequipment_equipment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereportequipment',
            name='new_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_equipment', to='wx.equipment'),
        ),
        migrations.AlterField(
            model_name='maintenancereportequipment',
            name='old_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_equipment', to='wx.equipment'),
        ),
    ]
