# Generated by Django 3.2.13 on 2026-05-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0068_auto_20260419_0540'),
    ]
    
    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS raw_data_station_variable_datetime_desc_valid_idx
                ON public.raw_data (station_id, variable_id, datetime DESC)
                WHERE measured > -99.9;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS public.raw_data_station_variable_datetime_desc_valid_idx;
            """,
        ),
    ]