# Generated by Django 3.2.13 on 2026-05-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0069_raw_data_prev_measured_index'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS wx_stationdataminimuminterval_station_variable_datetime_idx
                ON wx_stationdataminimuminterval (station_id, variable_id, datetime);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS wx_stationdataminimuminterval_station_variable_datetime_idx;
            """,
        ),

        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS raw_data_station_variable_datetime_idx
                ON raw_data (station_id, variable_id, datetime);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS raw_data_station_variable_datetime_idx;
            """,
        ),
    ]
