# Generated by Django 3.2.13 on 2026-05-19 05:17

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0070_add_data_inventory_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datetime', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('measured', models.FloatField()),
                ('seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StagedRawDataTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stationdatafile',
            old_name='is_historical_data',
            new_name='process_in_chunks',
        ),
        migrations.RenameField(
            model_name='stationfileingestion',
            old_name='is_historical_data',
            new_name='process_in_chunks',
        ),
        migrations.AddConstraint(
            model_name='stationdatafile',
            constraint=models.CheckConstraint(check=models.Q(('is_highfrequency_data', True), ('process_in_chunks', True), _negated=True), name='station_data_file_not_hf_and_chunked'),
        ),
        migrations.AddConstraint(
            model_name='stationfileingestion',
            constraint=models.CheckConstraint(check=models.Q(('is_highfrequency_data', True), ('process_in_chunks', True), _negated=True), name='station_file_ingestion_not_hf_and_chunked'),
        ),
        migrations.AddField(
            model_name='stagedrawdatatask',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.station'),
        ),
        migrations.AddField(
            model_name='stagedrawdatatask',
            name='station_data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.stationdatafile'),
        ),
        migrations.AddField(
            model_name='stagedrawdatatask',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.variable'),
        ),
        migrations.AddField(
            model_name='stagedrawdata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.station'),
        ),
        migrations.AddField(
            model_name='stagedrawdata',
            name='station_data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.stationdatafile'),
        ),
        migrations.AddField(
            model_name='stagedrawdata',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.variable'),
        ),
        migrations.AddIndex(
            model_name='stagedrawdatatask',
            index=models.Index(fields=['started_at', 'finished_at'], name='wx_stagedra_started_53ae08_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedrawdatatask',
            index=models.Index(fields=['station', 'variable', 'start_datetime', 'end_datetime'], name='wx_stagedra_station_128af4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stagedrawdatatask',
            unique_together={('station_data_file', 'station', 'variable', 'start_datetime', 'end_datetime')},
        ),
        migrations.AddIndex(
            model_name='stagedrawdata',
            index=models.Index(fields=['station_data_file', 'station', 'variable'], name='wx_stagedra_station_87742b_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedrawdata',
            index=models.Index(fields=['station', 'variable', 'datetime'], name='wx_stagedra_station_f22f03_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedrawdata',
            constraint=models.UniqueConstraint(fields=('station_data_file', 'datetime', 'station', 'variable'), name='unique_stagedrawdata_file_datetime_station_variable'),
        ),
    ]
