# Generated by Django 3.2.13 on 2026-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0071_auto_20260519_0517'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stagedrawdatatask',
            index=models.Index(fields=['station_data_file', 'station', 'variable'], name='wx_stagedra_station_ccbd66_idx'),
        ),
    ]
