# Generated by Django 3.2.13 on 2026-05-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0072_stagedrawdatatask_wx_stagedra_station_ccbd66_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS raw_data_station_variable_datetime_idx
                ON raw_data (station_id, variable_id, datetime DESC);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS raw_data_station_variable_datetime_idx;
            """,
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS raw_data_station_datetime_variable_idx
                ON raw_data (station_id, datetime DESC, variable_id);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS raw_data_station_datetime_variable_idx;
            """,
        ),
    ]