# Generated by Django 3.2.13 on 2026-05-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0073_add_monthly_capture_raw_data_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_reference',
            field=models.BooleanField(default=False, verbose_name='Reference Station'),
        ),
    ]
