# Generated by Django 3.2.13 on 2026-05-24 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0074_station_is_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.administrativeregion'),
        ),
    ]
