# Generated by Django 3.2.13 on 2026-05-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0075_alter_station_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationvariable',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.station'),
        ),
    ]
