# Generated by Django 3.2.13 on 2026-05-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0076_alter_stationvariable_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcpersistthreshold',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.station'),
        ),
        migrations.AlterField(
            model_name='qcpersistthreshold',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.variable'),
        ),
        migrations.AlterField(
            model_name='qcrangethreshold',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.station'),
        ),
        migrations.AlterField(
            model_name='qcrangethreshold',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.variable'),
        ),
        migrations.AlterField(
            model_name='qcstepthreshold',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.station'),
        ),
        migrations.AlterField(
            model_name='qcstepthreshold',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.variable'),
        ),
    ]
