# Generated by Django 3.2.13 on 2026-07-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0077_auto_20260524_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
