# Generated by Django 3.2.13 on 2026-09-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0078_delete_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynopTableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.variable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='synoptableconfiguration',
            constraint=models.UniqueConstraint(fields=('variable',), name='unique_synop_table_variable'),
        ),
        migrations.AddConstraint(
            model_name='synoptableconfiguration',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_synop_table_order'),
        ),
    ]
