# Generated by Django 3.2.13 on 2026-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0079_auto_20260922_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='persistence_window',
            field=models.IntegerField(default=96, verbose_name='Global threshold (Manual) Persistence Window (In hours. Default is 96 hours)'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='persistence_window_hourly',
            field=models.IntegerField(default=1, verbose_name='Global threshold (Automatic) Persistence Window (In hours. Default is 1 hour)'),
        ),
    ]
