# Generated by Django 3.2.13 on 2026-09-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0080_auto_20260925_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrangethreshold',
            name='range_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qcrangethreshold',
            name='range_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qcstepthreshold',
            name='step_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qcstepthreshold',
            name='step_min',
            field=models.FloatField(),
        ),
    ]
