# Generated by Django 3.2.13 on 2026-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0081_auto_20260926_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='elevation',
            field=models.FloatField(null=True, verbose_name='Elevation (m)'),
        ),
        migrations.RunSQL(
            sql='''
                ALTER TABLE public.raw_data
                ADD COLUMN proposed_value double precision,
                ADD COLUMN validated_remarks TEXT,
                ADD COLUMN validated_flag INTEGER,
                ADD COLUMN is_validated BOOLEAN DEFAULT FALSE NOT NULL;
            ''',
            reverse_sql='''
                ALTER TABLE public.raw_data
                DROP COLUMN proposed_value,
                DROP COLUMN validated_remarks,
                DROP COLUMN validated_flag,
                DROP COLUMN is_validated;
            '''
        ),
    ]
